apiVersion: v1
data:
  APP_PORT: "80"
kind: ConfigMap
metadata:
  name: news-config
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: news-service
  labels:
    app: news
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: news
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-deployment
spec:
  selector:
    matchLabels:
      app: news
  replicas: 1
  template:
    metadata:
      labels:
        app: news
    spec:
      containers:
      - name: news-pod
        image: gcr.io/vocal-tempo-259712/news:v1
        env:
          - name: APP_PORT
            valueFrom:
              configMapKeyRef:
                name: news-config
                key: APP_PORT
        ports:
        - containerPort: 80

